# frozen_string_literal: true

source "https://rubygems.org"
gem 'nokogiri'
gem 'rack', '~> 2.2.4'
gem 'rspec'

git_source(:github) {|repo_name| "https://github.com/nullzero-live/nullzero.github.io" }

# gem "rails"
